
-- Create cases table for detailed case studies
CREATE TABLE cases (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL UNIQUE,
  title_az TEXT NOT NULL,
  title_ru TEXT NOT NULL,
  title_en TEXT NOT NULL,
  client_name TEXT NOT NULL,
  industry_az TEXT NOT NULL,
  industry_ru TEXT NOT NULL,
  industry_en TEXT NOT NULL,
  service_type_az TEXT NOT NULL,
  service_type_ru TEXT NOT NULL,
  service_type_en TEXT NOT NULL,
  hero_image_url TEXT NOT NULL,
  challenge_az TEXT NOT NULL,
  challenge_ru TEXT NOT NULL,
  challenge_en TEXT NOT NULL,
  solution_az TEXT NOT NULL,
  solution_ru TEXT NOT NULL,
  solution_en TEXT NOT NULL,
  results_az TEXT NOT NULL,
  results_ru TEXT NOT NULL,
  results_en TEXT NOT NULL,
  before_image_url TEXT,
  after_image_url TEXT,
  video_url TEXT,
  metric1_value TEXT,
  metric1_label_az TEXT,
  metric1_label_ru TEXT,
  metric1_label_en TEXT,
  metric2_value TEXT,
  metric2_label_az TEXT,
  metric2_label_ru TEXT,
  metric2_label_en TEXT,
  metric3_value TEXT,
  metric3_label_az TEXT,
  metric3_label_ru TEXT,
  metric3_label_en TEXT,
  quote_text_az TEXT,
  quote_text_ru TEXT,
  quote_text_en TEXT,
  quote_author TEXT,
  quote_position TEXT,
  project_year INTEGER NOT NULL,
  is_featured BOOLEAN DEFAULT 0,
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample case studies
INSERT INTO cases (
  slug, title_az, title_ru, title_en, client_name,
  industry_az, industry_ru, industry_en,
  service_type_az, service_type_ru, service_type_en,
  hero_image_url, challenge_az, challenge_ru, challenge_en,
  solution_az, solution_ru, solution_en,
  results_az, results_ru, results_en,
  metric1_value, metric1_label_az, metric1_label_ru, metric1_label_en,
  metric2_value, metric2_label_az, metric2_label_ru, metric2_label_en,
  metric3_value, metric3_label_az, metric3_label_ru, metric3_label_en,
  quote_text_az, quote_text_ru, quote_text_en,
  quote_author, quote_position, project_year, is_featured, display_order
) VALUES
(
  'premium-auto-center',
  'Premium Auto Center - Rəqəmsal Transformasiya',
  'Premium Auto Center - Цифровая Трансформация',
  'Premium Auto Center - Digital Transformation',
  'Premium Auto Center',
  'Avtoservis', 'Автосервис', 'Auto Service',
  'SMM + Target Reklam', 'SMM + Таргетированная реклама', 'SMM + Targeted Ads',
  'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800',
  'Müştəri bazası azalır, rəqabət artır. Premium avtoservisin brendini gücləndirmək və daimi müştəri axını təmin etmək lazım idi.',
  'База клиентов сокращается, конкуренция растет. Нужно было усилить бренд премиум автосервиса и обеспечить постоянный поток клиентов.',
  'Client base declining, competition growing. Need to strengthen premium auto service brand and ensure steady client flow.',
  'Tam rəqəmsal strategiya: Instagram və Facebook-da premium məzmun, hədəfli reklam kampaniyaları, WhatsApp avtomatlaşdırma və müştəri loyallığı proqramı.',
  'Полная цифровая стратегия: премиум-контент в Instagram и Facebook, таргетированные рекламные кампании, автоматизация WhatsApp и программа лояльности клиентов.',
  'Complete digital strategy: premium content on Instagram and Facebook, targeted ad campaigns, WhatsApp automation and customer loyalty program.',
  '6 ayda sosial mediada 320% artım, aylıq 180+ yeni müştəri, CRM sistemi ilə 94% müştəri qaytarılması və servis rezervasiyalarında 250% artım.',
  'За 6 месяцев рост в соцсетях на 320%, ежемесячно 180+ новых клиентов, 94% возврат клиентов с CRM-системой и рост бронирований на 250%.',
  'In 6 months: 320% social media growth, 180+ new monthly clients, 94% client retention with CRM system and 250% increase in service bookings.',
  '+320%', 'sosial mediada artım', 'рост в соцсетях', 'social media growth',
  '180+', 'yeni müştəri/ay', 'новых клиентов/мес', 'new clients/month',
  '94%', 'müştəri qaytarılması', 'возврат клиентов', 'client retention',
  'B2Brand komandası ilə işləmək biznesin oyun dəyişdirici oldu. İlk aydan nəticələr görünməyə başladı.',
  'Работа с командой B2Brand стала game changer для бизнеса. Результаты стали видны с первого месяца.',
  'Working with B2Brand team was a game changer for the business. Results became visible from the first month.',
  'Elçin Məmmədov', 'Direktor, Premium Auto Center',
  2025, 1, 1
),
(
  'fashion-retail-branding',
  'Moda Boutique - Brenddən Rəqəmsal Platforma',
  'Moda Boutique - От бренда к цифровой платформе',
  'Fashion Boutique - From Brand to Digital Platform',
  'Moda Boutique',
  'Ticarət', 'Розничная торговля', 'Retail',
  'Brendinq + SMM + Video', 'Брендинг + SMM + Видео', 'Branding + SMM + Video',
  'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=800',
  'Yeni açılmış boutique üçün sıfırdan brend yaratmaq, onlayn satışı artırmaq və lokal bazarda tanınmaq lazım idi.',
  'Для нового бутика нужно было создать бренд с нуля, увеличить онлайн-продажи и добиться узнаваемости на локальном рынке.',
  'For a newly opened boutique, need to create brand from scratch, increase online sales and gain recognition in local market.',
  'Tam brend identifikasiyası (logo, rənglər, qablaşdırma), 3 aylıq video kampaniya, Instagram strategiyası və influencer əməkdaşlığı.',
  'Полная брендовая идентичность (логотип, цвета, упаковка), 3-месячная видео-кампания, стратегия Instagram и сотрудничество с инфлюенсерами.',
  'Complete brand identity (logo, colors, packaging), 3-month video campaign, Instagram strategy and influencer collaboration.',
  '4 ayda satışlar 180% artdı, Instagram izləyiciləri 8500-ə çatdı, boutique Bakının ən məşhur moda məkanlarından birinə çevrildi.',
  'За 4 месяца продажи выросли на 180%, подписчики Instagram достигли 8500, бутик стал одним из самых популярных модных мест Баку.',
  'In 4 months: sales increased 180%, Instagram followers reached 8500, boutique became one of most popular fashion spots in Baku.',
  '+180%', 'satış artımı', 'рост продаж', 'sales increase',
  '8500+', 'Instagram izləyicisi', 'подписчиков Instagram', 'Instagram followers',
  '42%', 'onlayn konversiya', 'онлайн-конверсия', 'online conversion',
  'Brendimiz B2Brand sayəsində həyat tapdı. Hər detal düşünülmüş, hər kampaniya nəticə verdi.',
  'Наш бренд ожил благодаря B2Brand. Каждая деталь продумана, каждая кампания принесла результат.',
  'Our brand came alive thanks to B2Brand. Every detail was thought through, every campaign delivered results.',
  'Aysel Hüseynova', 'Təsisçi, Moda Boutique',
  2025, 1, 2
),
(
  'tech-startup-launch',
  'TechFlow - Startapın Peşəkar Lansmanı',
  'TechFlow - Профессиональный запуск стартапа',
  'TechFlow - Professional Startup Launch',
  'TechFlow',
  'Startup', 'Стартап', 'Startup',
  'Target Reklam + AI Kontent', 'Таргетированная реклама + AI Контент', 'Targeted Ads + AI Content',
  'https://images.unsplash.com/photo-1551434678-e076c223a692?w=800',
  'Yeni SaaS startapı üçün sıfır auditoriyadan ilk 1000 istifadəçiyə çatmaq və investorların diqqətini çəkmək lazım idi.',
  'Для нового SaaS стартапа нужно было от нулевой аудитории достичь первых 1000 пользователей и привлечь внимание инвесторов.',
  'For a new SaaS startup, needed to reach first 1000 users from zero audience and attract investor attention.',
  'AI generativ kontent ilə hədəfli LinkedIn və Google Ads kampaniyaları, video explainer seriyası və investorlar üçün pitch deck hazırlanması.',
  'Таргетированные кампании LinkedIn и Google Ads с AI-генеративным контентом, серия видео-explainer и подготовка pitch deck для инвесторов.',
  'Targeted LinkedIn and Google Ads campaigns with AI generative content, explainer video series and pitch deck preparation for investors.',
  '3 ayda 1200+ qeydiyyat, 450+ aktiv istifadəçi, 2 investisiya təklifi və $120K ilkin investisiya.',
  'За 3 месяца 1200+ регистраций, 450+ активных пользователей, 2 инвестиционных предложения и $120K начальных инвестиций.',
  'In 3 months: 1200+ registrations, 450+ active users, 2 investment offers and $120K seed investment.',
  '1200+', 'qeydiyyat', 'регистраций', 'registrations',
  '450+', 'aktiv istifadəçi', 'активных пользователей', 'active users',
  '$120K', 'investisiya', 'инвестиций', 'investment',
  'B2Brand bizim startup yolculuğumuzun əsas tərəfdaşı oldu. Onlar olmadan bu qədər sürətli nəticə əldə edə bilməzdik.',
  'B2Brand стали ключевым партнером нашего стартап-путешествия. Без них мы не смогли бы достичь таких быстрых результатов.',
  'B2Brand became a key partner in our startup journey. Without them we could not achieve such fast results.',
  'Rəşad Əliyev', 'CEO, TechFlow',
  2024, 1, 3
),
(
  'consulting-company-video',
  'Business Konsaltinq - Korporativ Video Strategiyası',
  'Business Консалтинг - Корпоративная видео-стратегия',
  'Business Consulting - Corporate Video Strategy',
  'BizConsult Pro',
  'Xidmətlər', 'Услуги', 'Services',
  'Video İstehsal + SMM', 'Видеопродакшн + SMM', 'Video Production + SMM',
  'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800',
  'Konsaltinq şirkəti müştəri bazasını genişləndirmək və ekspert statusunu möhkəmləndirmək istəyirdi.',
  'Консалтинговая компания хотела расширить клиентскую базу и укрепить экспертный статус.',
  'Consulting company wanted to expand client base and strengthen expert status.',
  '12 epizodlu profesional video seriya "Biznes Həlləri", LinkedIn məzmun strategiyası və webinar kampaniyası.',
  '12-эпизодная профессиональная видео-серия "Бизнес-решения", контент-стратегия LinkedIn и вебинар-кампания.',
  '12-episode professional video series "Business Solutions", LinkedIn content strategy and webinar campaign.',
  '6 ayda 15 yeni korporativ müştəri, LinkedIn-də 200% artım, video seriyasını 45K+ insan izlədi.',
  'За 6 месяцев 15 новых корпоративных клиентов, рост в LinkedIn на 200%, видео-серию посмотрели 45K+ человек.',
  'In 6 months: 15 new corporate clients, 200% LinkedIn growth, video series watched by 45K+ people.',
  '15', 'yeni müştəri', 'новых клиентов', 'new clients',
  '+200%', 'LinkedIn artımı', 'рост LinkedIn', 'LinkedIn growth',
  '45K+', 'video baxış', 'просмотров видео', 'video views',
  'Video strategiyası biznesi tamamilə dəyişdi. İndi müştərilər bizə "o video şirkəti" kimi müraciət edirlər.',
  'Видео-стратегия полностью изменила бизнес. Теперь клиенты обращаются к нам как к "той видео-компании".',
  'Video strategy completely changed the business. Now clients refer to us as "that video company".',
  'Kamran Quliyev', 'Direktor, BizConsult Pro',
  2024, 0, 4
);
