/**
 * Augment Cloudflare Worker Env with secrets (set via wrangler secret / .dev.vars).
 * Merge with worker-configuration.d.ts generated by wrangler types.
 */
declare namespace Cloudflare {
  interface Env {
    /** Admin panel login password (required for local auth). */
    ADMIN_PASSWORD?: string;
    /** Secret used to sign session cookie (optional; if unset, ADMIN_PASSWORD is used to derive signature). */
    ADMIN_SESSION_SECRET?: string;
    SUPABASE_URL?: string;
    SUPABASE_SERVICE_ROLE_KEY?: string;
    /** Google Gemini API key for /api/chat (server-side only). */
    GEMINI_API_KEY?: string;
  }
}
